# Hello Openshift Ingress Canary service
# Specific values are applied at runtime
kind: Service
apiVersion: v1
# name and namespace are set at runtime.
spec:
  type: ClusterIP
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
